global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # FaceNet service metrics
  - job_name: 'facenet-service'
    static_configs:
      - targets: ['facenet-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # YOLOv8 service metrics
  - job_name: 'yolo-service'
    static_configs:
      - targets: ['yolo-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
