[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "docker-compose -f docker-compose.railway.yml up"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { RAILWAY_ENVIRONMENT = "production" }

[environments.staging]
variables = { RAILWAY_ENVIRONMENT = "staging" }
